# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-06 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_address_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='contact_number',
            field=models.CharField(max_length=120),
        ),
    ]
