# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-06 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20190506_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contact_number',
            field=models.CharField(default='09123123123', max_length=120),
        ),
    ]
