# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-07 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190402_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-title',)},
        ),
    ]
